version: '3.8'

services:
  website:
    image: $WEBSITE_IMAGE
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.$WEBSITE_SERVICE.loadbalancer.server.port=80"
        - "traefik.http.routers.$WEBSITE_SERVICE.rule=Host(`$WEBSITE_URL`, `www.$WEBSITE_URL`)"
        - "traefik.http.routers.$WEBSITE_SERVICE.entrypoints=websecure"
        - "traefik.http.routers.$WEBSITE_SERVICE.tls.certresolver=letsencrypt"
    networks:
      - traefik_webhost-swarm

networks:
  traefik_webhost-swarm:
    external: true